/**
 * Builds a fully self-contained KaTeX stylesheet for offline exports.
 *
 * Reads the KaTeX dist CSS, inlines every woff2 font face as a base64 data URI
 * (dropping the woff/ttf fallbacks to keep the payload small) and emits a
 * content-script-friendly module that hangs the CSS off `window.GEP.katex`.
 *
 * Run with: node scripts/build-katex.mjs
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");
const distDir = resolve(root, "node_modules", "katex", "dist");
const cssPath = resolve(distDir, "katex.min.css");
const fontsDir = resolve(distDir, "fonts");
const pkg = JSON.parse(readFileSync(resolve(root, "node_modules", "katex", "package.json"), "utf8"));

let css = readFileSync(cssPath, "utf8");

// Inline the woff2 sources as data URIs.
const woff2Cache = new Map();
css = css.replace(/url\(fonts\/([^)]+\.woff2)\)/g, (_m, file) => {
  if (!woff2Cache.has(file)) {
    const buf = readFileSync(resolve(fontsDir, file));
    woff2Cache.set(file, buf.toString("base64"));
  }
  return `url(data:font/woff2;base64,${woff2Cache.get(file)})`;
});

// Drop the woff and ttf fallbacks now that woff2 is inlined.
css = css.replace(/,url\(fonts\/[^)]+\.woff\)\s*format\("woff"\)/g, "");
css = css.replace(/,url\(fonts\/[^)]+\.ttf\)\s*format\("truetype"\)/g, "");

if (/url\(fonts\//.test(css)) {
  throw new Error("Leftover relative font reference after inlining; aborting.");
}

const banner =
  "/* AUTO-GENERATED by scripts/build-katex.mjs — do not edit by hand. */\n" +
  `/* KaTeX v${pkg.version} stylesheet with woff2 fonts inlined as data URIs. */\n`;

const out =
  banner +
  "(function () {\n" +
  '  "use strict";\n' +
  "  const GEP = (window.GEP = window.GEP || {});\n" +
  `  GEP.katex = { version: ${JSON.stringify(pkg.version)}, css: ${JSON.stringify(css)} };\n` +
  "})();\n";

const outPath = resolve(root, "src", "vendor", "katex.js");
writeFileSync(outPath, out, "utf8");

const kb = (Buffer.byteLength(out, "utf8") / 1024).toFixed(1);
console.log(`Wrote ${outPath} (${kb} KB, ${woff2Cache.size} fonts inlined).`);
